### ISSUE TITLE
Fintium FinTech Challenge one page website design

### ISSUE THREAD

**Issue by guylepage3** [universelabs/universe-design2#17]
### Task
Design a one page website for the Fintium FinTech Challenge event for Friday, Apr 19 at 5pm.

### Event Description
Fintium FinTech Challenge matches top University students with Fortune 500 Tech and FinTech companies.

### Creative Brief

The following questions will assist in defining the UI look and feel of the product.

1. What problem(s) do users have?
    - Users need to find out information about the event in a quick concise manner.
2. What are the solution(s)?
    - Provide them with a simple, clean and easy to read informational website.
3. Who is the targeted audience? (List all targets)
    - Fortune 500 executives from companies such as Microsoft, Amazon, etc.
    - Tech and business professors from the top Universities such as Harvard, MIT, etc.
    - Top Engineers and MBA students
    - Top FinTech CEO's
4. What are the immediate goal(s)?
    - Design a clean and simple brand and UI for users to get to the information they need as fast as possible.
5. Define main metric of success
    - Folks are able to find what they need.
6. Example sites? (List all in order of significance w/URL’s)
    - GitHub + https://githubuniverse.com/2018/
    - Consensys + https://etherealsummit.com/
    - Apple + https://developer.apple.com/wwdc19/
    - Websummit + https://websummit.com/
    - Dublin Tech Summit + https://dublintechsummit.com/
    - CES + https://www.ces.tech/
7. What is the desired image? Do you know of something you’d like this project to resemble?
    - Site has to be easy to read and designed for audience.
10. Do you have any product that you think you’d like to resemble?
    - GitHub Universe Event + https://githubuniverse.com/2018/
    - Ethereal Summit + https://etherealsummit.com/
    - Apple WWDC + https://developer.apple.com/wwdc19/
    - Websummit + https://websummit.com/
    - Dublin Tech Summit + https://dublintechsummit.com/
    - CES + https://www.ces.tech/
11. Are there any possible barriers or hurdles to the design of the product? If so, what are they?
    - The site has to be a one page website.
12. What dynamics are you looking to add to enhance the product? (ie. 3d graph, live chat, etc.)
    - Nothing
13. How will you drive people to the product?
    - People will be landing on the home page through invitation.
14. How will it be marketed?
    - Through word of mouth
15. Visual descriptive words: Choose 3 words to describe how you visualize the look and feel of the product. – Please use adjectives and/or attitudinal traits (I.E. cheeky, clean, rustic, bold, etc...)
    - Clean, Readable, Cool.

**Comment by guylepage3** [comment]
Hey @pftchal, Please find the instructions above for the one page website design. Please do not hesitate to message me if you have any questions.

**Comment by guylepage3** [comment]
Please remember this first round is just about the design and UI. Content does not matter right now.

**Comment by pftchal** [comment]
Got it!

**Comment by pftchal** [comment]
Hi Guy,

Do you think the nav bar be like this is ok: 
ABOUT  SPEAKERS  SCHEDULE  SPONSOR  CONTACT

**Comment by guylepage3** [comment]
>Do you think the nav bar be like this is ok:
>ABOUT SPEAKERS SCHEDULE SPONSOR CONTACT

Yes. That sounds good @pftchal :)

**Comment by pftchal** [comment]
[FintiumFintech_Wireframe.pdf](https://github.com/universelabs/universe-design/files/3096373/FintiumFintech_Wireframe.pdf)

Hi Guy,

I have created a basic version without too many graphics in Sketch, let me know how do you feel about this layout and overall look. I also created a simple logo while I was playing around with the design. Let me know how you think and if there is anything that you want me to change. And then I will move on adding colors and some graphics.

**Comment by guylepage3** [comment]
Hey @pftchal.. This is a good start.

Here are my comments:
1. I would not work on the logo anymore. We will just use the one the other designer created.
2. I would reduce the font sizes.
3. All the content will be on just this one page so we can remove...
    - Complete schedule
    - See more guests

Let's add some graphics and see where we end up from here. The placement of the content is well placed. Excited to see the next iteration. :)

**Comment by pftchal** [comment]
[FintiumFintechDesign1.zip](https://github.com/universelabs/universe-design/files/3098856/FintiumFintechDesign1.zip)

Hi Guy,

I played around added colors sketches and pictures. The illustrations are sketch sources found online that can be used on any real projects and I made a few changes to them as well. Let me know how you think and I have also made font sizes smaller.

**Comment by guylepage3** [comment]
### Changes - Set 1 of 2

Great start @pftchal.. 

- Let's reduce the font size on the navbar,
- Get rid of gradients and pastel colors. The demographic skews male.
- I noticed you're using https://www.humaaans.com/. I LOVE the contrast and cleanliness of their site. See screen shots below. Let's go with that color palette.
- Let's go with the contact form we are using on http://universe.engineering
- Each sponsor logo should be bigger by almost double. Maybe reduce the number of logos by half.
<img width="663" alt="Screenshot 2019-04-19 13 57 12" src="https://user-images.githubusercontent.com/1711854/56437099-2f5c8400-62ac-11e9-8d43-902eac5e5cfc.png">
<img width="1885" alt="Screenshot 2019-04-19 13 57 32" src="https://user-images.githubusercontent.com/1711854/56437100-2f5c8400-62ac-11e9-8d90-856019807e6c.png">
<img width="1908" alt="Screenshot 2019-04-19 13 57 41" src="https://user-images.githubusercontent.com/1711854/56437101-2f5c8400-62ac-11e9-8b84-7ef29dc45f56.png">

**Comment by guylepage3** [comment]
If you can make the above changes quickly and send it to me then I'll present it to Matt.

**Comment by pftchal** [comment]
@guylepage3 Sure. I will make changes accordingly! thanks for the comments, appreciate it. Also, when do you need the next version? Still today or can I make changes over the weekend?

**Comment by guylepage3** [comment]
@pftchal can you see the above comment? Let's make those changes above as fast as possible. Doesn't need to be perfect.

**Comment by pftchal** [comment]
@guylepage3 ok. Give me a few hours :)

**Comment by guylepage3** [comment]
Thank you @pftchal... :)

**Comment by guylepage3** [comment]
### Changes - Set 2 of 2

This weekend and Monday... Let's have you really think hard about the below comments on the Hero section and have something ready for Tuesday on the items below.

- Lastly.. The hero section should be full screen color and the illustration should not be fun but more serious. See the WWDC screen shot from apple below.
- I would make sure that the feel is not fun and playful. There are major world companies and their executives attending the event. Let's stay clear of "fun" and go with edgy or cool / modern.

<img width="1913" alt="Screenshot 2019-04-19 14 05 11" src="https://user-images.githubusercontent.com/1711854/56437216-84989580-62ac-11e9-998f-dd263374d668.png">

**Comment by pftchal** [comment]
@guylepage3 Ok sounds good, So I will send the next version to you Monday? I might send you something before that and see if we can make other changes, does that work?

**Comment by guylepage3** [comment]
@pftchal As stated in Slack.. There are 2 sets of changes to be made above..

**Changes - Set 1**
- Let’s have you work on those changes as fast as possible today. For delivery to me today.

**Changes - Set 2**
- The second set of changes are to be ready for Tuesday.

**Comment by pftchal** [comment]
@guylepage3 got it!

**Comment by guylepage3** [comment]
Just placing some logos here..

![image](https://user-images.githubusercontent.com/1711854/56444119-7440e480-62c5-11e9-91f2-d9a1feea93a2.png)
![image](https://user-images.githubusercontent.com/1711854/56444157-976b9400-62c5-11e9-8db2-0fb68720c78f.png)
![image](https://user-images.githubusercontent.com/1711854/56444169-9d617500-62c5-11e9-9758-ae012ba33b4c.png)
![image](https://user-images.githubusercontent.com/1711854/56444214-cc77e680-62c5-11e9-9998-fb86d706c2b8.png)
![image](https://user-images.githubusercontent.com/1711854/56444238-e9acb500-62c5-11e9-82c9-eb8d51b0dfc0.png)
![image](https://user-images.githubusercontent.com/1711854/56444489-00074080-62c7-11e9-9d64-a69a620fc785.png)

**Comment by pftchal** [comment]
@guylepage3 thanks for the logos. This is the updated design! : 

[FintiumFintechDesign2.zip](https://github.com/universelabs/universe-design/files/3099328/FintiumFintechDesign2.zip)

**Comment by guylepage3** [comment]
Transcript from Slack...

Charlotte Pan [5:18 PM]
@guylepage3  hi guy just sent you an updated design!

Guy Lepage [5:19 PM]
Thank you @pftchal Looking now. :slightly_smiling_face:
MUCH better!!

This is a really good start..
I’m going to make a few small tweaks and present this to Matt this weekend.
In the meantime, we need to focus on the navbar and hero area… It’s looking a lot better but we can make it even stronger.. :slightly_smiling_face:
I don’t think you need to work on this this weekend though. Take the weekend off for yourself and we can work hard on it on Monday.

**Comment by guylepage3** [comment]
New Fintium FinTech Challenge logo..


<img width="1289" alt="fintium-logo-v1 0 0" src="https://user-images.githubusercontent.com/1711854/56462567-4cb84d80-6393-11e9-8527-2b264e56d1b4.png">

**Comment by guylepage3** [comment]
![fintium-web-v1 2 0@2x](https://user-images.githubusercontent.com/1711854/56510513-05979d00-64f8-11e9-8c07-602b593bec63.png)

**Comment by guylepage3** [comment]
@pftchal, Here's the latest version of the website design.. https://github.com/universelabs/universe-design/blob/master/events/09-19-fintium-fintech-challenge/fintium-web-v1.2.0.sketch

Can we get you to 
- Reduce the size of the sponsor images by 20-30%
- Update the footer content

Once done please upload to this issue and then I'll present it to Matt and team.

Great work here! 👍

**Comment by guylepage3** [comment]
Also, @pftchal can you add "FinTech Challenge" to the logo? Thank you.

**Comment by pftchal** [comment]
@guylepage3 hi guy, you need me to add "Fintech Challenge" to the logos on the web design, correct? or also to the logo picture itself?

**Comment by guylepage3** [comment]
Let's just go with the website design for now @pftchal. Thank you.

**Comment by guylepage3** [comment]
@pftchal, @aseoconnor will be guiding you through content, wording and anything else needed from here on in.

**Comment by pftchal** [comment]
@guylepage3 @aseoconnor Awesome!

**Comment by pftchal** [comment]
[fintium-web-v1.2.1.zip](https://github.com/universelabs/universe-design/files/3104723/fintium-web-v1.2.1.zip)

@guylepage3 Hi Guy! I have made the changes. Please take a look at it and let me know how you think :)

**Comment by guylepage3** [comment]
![fintium-web-v1 2 2@2x](https://user-images.githubusercontent.com/1711854/56531534-35f43100-6522-11e9-8c74-cd5367ac0566.png)

**Comment by guylepage3** [comment]
@pftchal, I adjusted the following;

- Reduced the size of the speakers
- Designed a new graphic for the hero section
- Repositioned the FinTech Challenge under the logo
- Adjusted the footer content.
- Cleaned up the about section items to fit the new grid.

**Comment by guylepage3** [comment]
@pftchal can you play with the new hero graphic so that the type is more legible. Maybe do 3-4 different layouts?

We're getting there.. :)

**Comment by pftchal** [comment]
@guylepage3 thanks. Nice job! Did you use Illustrator to create the new graphic?

Yes, I will work on it tonight!

**Comment by guylepage3** [comment]
Here's the latest file @pftchal https://github.com/universelabs/universe-design/blob/master/events/09-19-fintium-fintech-challenge/fintium-web-v1.2.2.sketch

**Comment by guylepage3** [comment]
@pftchal I used Illustrator and Photoshop for the Gausian Blur. Would you like the illustrator file?

**Comment by pftchal** [comment]
@guylepage3 Yes please, would like to take a look :) thanks

**Comment by guylepage3** [comment]
here's the illustrator file. :) https://github.com/universelabs/universe-design/tree/master/events/09-19-fintium-fintech-challenge/support

**Comment by aseoconnor** [comment]
@pftchal I made some copy edits to the page =) 

[fintium-web-v1.2.1-CopyEdits.pdf](https://github.com/universelabs/universe-design/files/3105031/fintium-web-v1.2.1-CopyEdits.pdf)

**Comment by pftchal** [comment]
@aseoconnor Got it thanks! @guylepage3

**Comment by pftchal** [comment]
[fintium-web-v1.2.3 part1.sketch.zip](https://github.com/universelabs/universe-design/files/3105478/fintium-web-v1.2.3.part1.sketch.zip)
[fintium-web-v1.2.3 part2.sketch.zip](https://github.com/universelabs/universe-design/files/3105479/fintium-web-v1.2.3.part2.sketch.zip)

@guylepage3 I played around the layouts of the hero section and there are four layout ideas that I came up with. I did not change the graphic itself too much.
 @aseoconnor I have added the copy text! Just the headline of the hero section, we can come up with more ideas here to make it stronger :)

**Comment by guylepage3** [comment]
Hey Charlotte, I’m taking a look at the designs now. :)

**Comment by pftchal** [comment]
[part1.zip](https://github.com/universelabs/universe-design/files/3108062/part1.zip)

part 1

**Comment by pftchal** [comment]
[part2.zip](https://github.com/universelabs/universe-design/files/3108063/part2.zip)

part 2

**Comment by guylepage3** [comment]
Thanks @pftchal.. This was a good start. So I took your [`fintium-web-v1.3.1`](https://github.com/universelabs/universe-design/blob/master/events/09-19-fintium-fintech-challenge/versions/fintium-web-v1.3.1.sketch) and adjusted it a bit for legibility here.. [`fintium-web-v1.4.0`](https://github.com/universelabs/universe-design/blob/master/events/09-19-fintium-fintech-challenge/fintium-web-v1.4.0.sketch). I will present this to Matt and team today.. 

Great work here. 👍 

While I'm presenting this to Matt and folks, can you work on the illustration a bit to make it work for the space? I basically took an old illustration I had and created a certain style. Can you provide a couple illustrations completed in this style?

**Comment by pftchal** [comment]
@guylepage3 Thanks! I will play around! I don't have much graphc design background, but I think I can experiment a little bit. :)

**Comment by pftchal** [comment]
[Illustration.zip](https://github.com/universelabs/universe-design/files/3119127/Illustration.zip)


Hi @guylepage3 I watched some tutorials and created two graphics, let me know how you think. I might play around more tomorrow

**Comment by guylepage3** [comment]
Taking a look now @pftchal

**Comment by guylepage3** [comment]
These are quite a bit off from our style we are looking for. We're looking for something like what we see below..

<img width="716" alt="Screenshot 2019-04-27 16 09 13" src="https://user-images.githubusercontent.com/1711854/56854581-d7a2c600-6906-11e9-8e13-6457eda6c62c.png">
<img width="1907" alt="Screenshot 2019-04-27 16 09 26" src="https://user-images.githubusercontent.com/1711854/56854583-d7a2c600-6906-11e9-9c66-bdeb278c7723.png">

**Comment by guylepage3** [comment]
I think I'll work on the illustration tomorrow and layout.. Then we can start building from there next week. 😄

**Comment by pftchal** [comment]
Sounds great! Let me know what I can start helping with and working on!

**Comment by guylepage3** [comment]
![fintium-web-v2 0 3@2x](https://user-images.githubusercontent.com/1711854/56981347-a9162c80-6b4c-11e9-8010-c320ee65657e.png)

**Comment by guylepage3** [comment]
Closing this issue. Opening a new issue for the design of the content here. https://github.com/universelabs/universe-design2/issues/18
