### ISSUE TITLE
Add 'forgot password' to login page

### ISSUE THREAD

**Issue by pftchal** [universelabs/universe-design2#33]
**Description**
I forgot my password today, so I will have to sign up again.
When users forget their password, there is not yet a way to reset the password. Adding 'forget password?' and sending users email to reset the password will help. 

Also, I think there is no need to redirect the users to another page when they enter the wrong email address or wrong password, just simply add a text in red under 
<img width="1239" alt="Screen Shot 2019-07-15 at 3 18 51 PM" src="https://user-images.githubusercontent.com/48525282/61243034-1893c500-a715-11e9-9c48-587e89b7c19b.png">

**Tasks**
- [Add 'forgot password' ] This is the first task
- [Instead of redirecting to another page, just notify users on the same page that the password/username they enter is wrong ] This is the second task

Any other information you want to share that is relevant to the issue. This might include the lines of code, screenshots, imagery, links, solutions, opinions, feedback, etc.

**Comment by guylepage3** [comment]
Nice @pftchal 

Authentication revisit in Sprint 7.
