### ISSUE TITLE
Set up different statements for different errors

### ISSUE THREAD

**Issue by pftchal** [universelabs/universe-design2#34]
**Description**
So I tried to sign up with the same email address that I used before. It showed the same error page. It will be better if the website can tell the users: "this email address has been used, please use another email address." It will be frustrating to see the same error page and the users have to guess what exactly is the problem. Instead, we can tell them what they have done wrong.

Screenshot:
<img width="1239" alt="Screen Shot 2019-07-15 at 3 18 51 PM" src="https://user-images.githubusercontent.com/48525282/61243804-c3f14980-a716-11e9-8390-6210fd5fe0ca.png">

**Comment by guylepage3** [comment]
Great @pftchal Let's you and I address this issue in Sprint 6.
