### ISSUE TITLE
Suggest password strength when signing up

### ISSUE THREAD

**Issue by pftchal** [universelabs/universe-design2#35]
**Description**
When users sign up for the first time, the website can suggest that if the password they set up is strong and safe enough. For a platform that is managing really important keys, I feel like it has the responsibility to remind users that their passwords might not be safe enough. What if I just enter 12345678 as my password? A user can easily lose trust in this app if the website allows them to do that. And I just tried, the website allowed me to use 123 as my password. For example, suggesting them to use a combination of the uppercase letter, numbers and _ @ - etc. Also when they enter the password, give them advice if it is a strong or weak password.

**Comment by guylepage3** [comment]
Good point @pftchal. Assigning this to Sprint 6.
