### ISSUE TITLE
Key UI on mobile

### ISSUE THREAD

**Issue by pftchal** [universelabs/universe-design2#36]
**Description**
The font size of the keys on the mobile looks a bit bulky to me. The first tab Blockstack is showing the key in full, while the Bitcoin and Ethereum are not displaying the keys in full. I am not sure if it was designed on purpose, for a user, if I cannot view my entire keys but only part of them on the web page, I might think it is an error. Making the keys draggable from left to right will be one solution, or making the font size of keys smaller is another.

**Comment by guylepage3** [comment]
@pftchal good point.
