### ISSUE TITLE
Make expanding/closing tabs easier

### ISSUE THREAD

**Issue by pftchal** [universelabs/universe-design2#37]
**Description**
Right now if I open all the tabs, and I want to close them all, I will have to click them one by one. It will be easier to have a button next to "YOUR KEYS" that the users can close all the tabs in one click, for better security. 

Screenshot: (An example)

<img width="644" alt="Screen Shot 2019-07-15 at 5 13 24 PM" src="https://user-images.githubusercontent.com/48525282/61249690-e9388480-a723-11e9-84b0-d9a98b89a0bd.png">

**Comment by guylepage3** [comment]
Good point @pftchal
